---
".gitlab-ci.yml":
  delete: true
".rubocop.yml":
  profiles:
    strict:
      configs:
        Style/GlobalVars:
          Exclude:
          - spec/**/*
".travis.yml":
  stages:
    - static
    - spec
  deploy_to_forge:
    enabled: false
  global_env:
  - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  simplecov: true
  notifications:
    slack:
      secure: OviSgQ0iGIHgjC8eiiRrqDV958sNSE0te+Q8IdPgxJZwMYYeP3hCW6e8ngl5op1GTIUoiMZwMfcXTHJmq71BkBUkRQlfmFw5onTlqs2xitCA8nQvo0PKLWcgr9X9R6A1NZCiPg0BTy6JDApIYq1WfVCWLuoRQyJCT07V6mpYjCI=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  use_litmus: true
  spec_type: spec
  matrix_extras:
  - PUPPET_GEM_VERSION: "~> 6.0"
    RUBY_VERSION: 25
    CHECK: parallel_spec
  - PUPPET_GEM_VERSION: "~> 6.0"
    RUBY_VERSION: 25-x64
    CHECK: parallel_spec
  simplecov: true
Gemfile:
  optional:
    ":development":
      - gem: github_changelog_generator
Rakefile:
  changelog_user: puppetlabs
  changelog_since_tag: 2.1.2
  extras: |
    if Rake::Task.task_defined?('spec_prep')
      Rake::Task.tasks.each do |task|
        next unless task.name.start_with? 'litmus:acceptance'
        task.enhance([Rake::Task['spec_prep']])
      end
    end
spec/spec_helper.rb:
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false

.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
